# Generated by Django 6.0 on 2025-12-20 05:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_alter_category_options_remove_category_subkat_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
            ],
            options={
                'verbose_name': 'Индекс видео',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('intro', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание (под видео)')),
                ('boomstream_code', models.CharField(max_length=50, verbose_name='Код Boomstream (например, reQuguw0)')),
                ('embed_type', models.PositiveSmallIntegerField(choices=[(1, 'Простой iframe в div (рекомендуется)'), (2, 'Script + span'), (3, 'Iframe с ?color=false')], default=1, verbose_name='Тип эмбеда')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'section': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_pages', to='blog.category', verbose_name='Категория')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Превью-изображение')),
            ],
            options={
                'verbose_name': 'Видео',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
