# Generated by Django 6.0 on 2025-12-24 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopage',
            name='boomstream_code',
            field=models.CharField(default='D6K46zjA', max_length=50, verbose_name='Код Boomstream'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='date',
            field=models.DateField(default=datetime.date(2025, 12, 25), verbose_name='Дата публикации'),
        ),
    ]
