# Generated by Django 6.0 on 2025-12-20 08:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_alter_category_options_remove_category_subkat_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
            ],
            options={
                'verbose_name': 'Индекс аудио уроков',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Длительность (например, 15:34)')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Описание урока')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка на аудио (если не файл)')),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Аудио-файл (mp3)')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'section': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_pages', to='blog.category', verbose_name='Категория')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Аудио урок',
            },
            bases=('wagtailcore.page',),
        ),
    ]
