# Generated by Django 6.0 on 2025-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopage',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Внешняя ссылка на аудио '),
        ),
    ]
