# Generated by Django 6.0 on 2025-12-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_audiopage_external_url'),
        ('blog', '0002_alter_category_options_remove_category_subkat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopage',
            name='category',
            field=models.ForeignKey(blank=True, default=7, limit_choices_to={'section': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_pages', to='blog.category', verbose_name='Категория'),
        ),
    ]
