# Generated by Django 6.0 on 2025-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='subkat',
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Блог'), (2, 'Видео'), (3, 'Аудио'), (4, 'Курсы/Учеба')], default=1, verbose_name='Раздел контента'),
        ),
    ]
