# Generated by Django 6.0 on 2025-12-17 06:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content_blocks', wagtail.fields.StreamField([('hero', 2), ('section', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фоновое изображение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 4), ('image', 5), ('show_button', 6), ('button_text', 7)]], {})}, verbose_name='Контент (блоки)')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
