# Generated by Django 6.0 on 2025-12-17 14:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Краткое введение')),
                ('body', wagtail.fields.StreamField([('section', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 2), ('show_button', 3), ('button_text', 4)]], {})}, verbose_name='Контент раздела')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
