# Generated by Django 6.0 on 2025-12-19 06:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sectionpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение (над списком групп)')),
                ('section_type', models.PositiveSmallIntegerField(choices=[(1, 'Световые частоты'), (2, 'Космоэнергетика')], help_text='Выберите, какие группы показывать на этой странице', verbose_name='Тип раздела частот')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('hero', 2), ('section', 8), ('text_only', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фоновое изображение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 4), ('image', 5), ('show_button', 6), ('button_text', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('content', 11)]], {})}, verbose_name='Контент (блоки)'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 5), ('text_only', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 2), ('show_button', 3), ('button_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('content', 8)]], {})}, verbose_name='Контент раздела'),
        ),
    ]
