# Generated by Django 6.0 on 2025-12-19 14:23

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_channelsectionpage_alter_homepage_content_blocks_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchangelsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение ')),
            ],
            options={
                'verbose_name': 'Блок энергий 95 Архангелов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='channelsectionpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Введение '),
        ),
        migrations.AlterField(
            model_name='channelsectionpage',
            name='section_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Световые частоты'), (2, 'Космоэнергетика')], help_text='Выберите группы', verbose_name='Тип раздела частот'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('hero', 2), ('section', 8), ('text_only', 12), ('width_button', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фоновое изображение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 4), ('image', 5), ('show_button', 6), ('button_text', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('content', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('button_text', 13), ('link_page', 14)]], {})}, verbose_name='Контент (блоки)'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 5), ('text_only', 9), ('width_button', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 2), ('show_button', 3), ('button_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('content', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 11: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('button_text', 10), ('link_page', 11)]], {})}, verbose_name='Контент раздела'),
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.PositiveIntegerField(default=0, verbose_name='ID (порядковый номер)')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='home.archangelspage')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
