# Generated by Django 6.0 on 2026-01-08 13:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_archangelspage_alter_channelsectionpage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('hero', 2), ('section', 10), ('text_only', 14), ('width_button', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фоновое изображение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Уникальный идентификатор только из латиницы, цифр, дефисов и подчёркиваний.', 'label': 'Якорь (ID для ссылок)', 'max_length': 54, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('anchor', 3), ('title', 4), ('text', 5), ('image', 6), ('show_button', 7), ('button_text', 8), ('button_page', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 13: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('anchor', 3), ('title', 11), ('description', 12), ('content', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 16: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('button_text', 15), ('link_page', 16)]], {})}, verbose_name='Контент (блоки)'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 7), ('text_only', 11), ('width_button', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Уникальный идентификатор только из латиницы, цифр, дефисов и подчёркиваний.', 'label': 'Якорь (ID для ссылок)', 'max_length': 54, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('text', 2), ('image', 3), ('show_button', 4), ('button_text', 5), ('button_page', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 8), ('description', 9), ('content', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 13: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('button_text', 12), ('link_page', 13)]], {})}, verbose_name='Контент раздела'),
        ),
    ]
