# Generated by Django 6.0.1 on 2026-02-15 12:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_archangelspage_search_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsectionpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 7), ('text_only', 11), ('width_button', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Уникальный идентификатор только из латиницы, цифр, дефисов и подчёркиваний.', 'label': 'Якорь (ID для ссылок)', 'max_length': 54, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст (слева)', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение (справа)', 'required': True}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Показывать кнопку «Подробнее»', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('text', 2), ('image', 3), ('show_button', 4), ('button_text', 5), ('button_page', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Короткое описание (подзаголовок)', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Основной текст', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 8), ('description', 9), ('content', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 13: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('button_text', 12), ('link_page', 13)]], {})}, verbose_name='Контент раздела'),
        ),
    ]
