# Generated by Django 6.0 on 2025-12-19 06:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы (Матрица / Блок)')),
                ('description', models.TextField(blank=True, verbose_name='Короткое описание группы')),
                ('section', models.PositiveSmallIntegerField(choices=[(1, 'Световые частоты'), (2, 'Космоэнергетика')], verbose_name='Раздел')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядковый номер группы')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение (значок группы)')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=200, verbose_name='Название канала / частоты')),
                ('description', models.TextField(blank=True, verbose_name='Короткое описание (для таблицы)')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Полное содержание (раскрываемый текст)')),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='channels.channelgroup')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
