# Generated by Django 6.0 on 2025-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroup',
            name='old_katg',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Старый ID группы (katg из alsfera_canal)'),
        ),
    ]
