# Generated by Django 6.0 on 2025-12-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channelgroup_old_katg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelgroup',
            name='old_katg',
        ),
    ]
