# Generated by Django 6.0.1 on 2026-02-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_remove_channelgroup_old_katg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа канала')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядковый номер (для сортировки)')),
            ],
            options={
                'verbose_name': 'Тип канала',
                'verbose_name_plural': 'Типы каналов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='fchannel',
            options={'ordering': ['sort_order'], 'verbose_name': 'Канал / Частота', 'verbose_name_plural': 'Каналы / Частоты'},
        ),
        migrations.AddField(
            model_name='fchannel',
            name='chtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='channels.channeltype', verbose_name='Тип канала'),
        ),
    ]
